### ISSUE TITLE
stuck Starting item.dat reading..

### ISSUE THREAD

**Issue by GuckTubeYT** [DrOreo002/GrowtopiaItemDataTools#4]
stuck Starting item.dat reading..

**Comment by GuckTubeYT** [comment]
13:35:53 [INFO] Command help has been registered!
13:35:53 [INFO] Command item has been registered!
13:35:53 [INFO] Command build-description has been registered!
13:35:53 [INFO] Command build-name has been registered!
13:35:53 [INFO] Config has been loaded! (config.json)
13:35:53 [INFO] Getting items.dat on C:\Users\GuckTubeYT\AppData\Local
13:35:53 [INFO]
13:35:53 [INFO] Version: 11
Exception in thread "main" java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
        at me.droreo002.tools.ItemDataDecoder.run(ItemDataDecoder.java:179)
13:35:53 [INFO]         at me.droreo002.tools.ItemDataDecoder.main(ItemDataDecoder.java:55)
Hash: -1331872251
13:35:53 [INFO] Item Count: 9304
13:35:53 [INFO] Starting item.dat reading..
This is log

**Comment by DrOreo002** [comment]
Your java version?

**Comment by GuckTubeYT** [comment]
jdk

**Comment by GuckTubeYT** [comment]
> 
> 
> Your java version?

my java version is jdk

**Comment by DrOreo002** [comment]
> > Your java version?
> 
> my java version is jdk

No I mean Java 8 or?

**Comment by GuckTubeYT** [comment]
> 
> 
> > > Your java version?
> > 
> > 
> > my java version is jdk
> 
> No I mean Java 8 or?
java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) Client VM (build 25.231-b11, mixed mode, sharing)

**Comment by GuckTubeYT** [comment]
> 
> 
> > > Your java version?
> > 
> > 
> > my java version is jdk
> 
> No I mean Java 8 or?

java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) Client VM (build 25.231-b11, mixed mode, sharing)

**Comment by DrOreo002** [comment]
Cant seem to replicate your issue.. I'm also running on the same version as yours

**Comment by GuckTubeYT** [comment]
but, why i stuck

**Comment by DrOreo002** [comment]
> but, why i stuck

I do not know. Its working fine on me.

**Comment by GuckTubeYT** [comment]
Exception in thread "main" java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
        at me.droreo002.tools.ItemDataDecoder.run(ItemDataDecoder.java:179)
18:43:46 [INFO]         at me.droreo002.tools.ItemDataDecoder.main(ItemDataDecoder.java:55)

**Comment by GuckTubeYT** [comment]
btw, how to change path?

**Comment by DrOreo002** [comment]
> Exception in thread "main" java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
> at me.droreo002.tools.ItemDataDecoder.run(ItemDataDecoder.java:179)
> 18:43:46 [INFO] at me.droreo002.tools.ItemDataDecoder.main(ItemDataDecoder.java:55)

Lu indo, jan paksa dah ngomong inggris :v, bukan brarti jelek ya cuman ya biar gampang aja ngertinya.

Itu errornya NoSuchMethodError artinya methodnya ga ditemukan. Spekulasi w itu ya Java ver lu engga 1.8 jadinya method #position itu engga di temuin. Tapi lu bilang make 1.8 yaudah kan ya jadinya w engga tau kenapa.

**Comment by DrOreo002** [comment]
> btw, how to change path?

What path?

**Comment by GuckTubeYT** [comment]
change this
C:\Users\GuckTubeYT\AppData\Local
to this
C:\Users\GuckTubeYT\Desktop

**Comment by GuckTubeYT** [comment]
and where i throw items.dat?

**Comment by DrOreo002** [comment]
> change this
> C:\Users\GuckTubeYT\AppData\Local
> to this
> C:\Users\GuckTubeYT\Desktop

Go to the code and find it by yourself. I'm not here to spoonfeed you, sorry. 

> and where i throw items.dat?

Like I said earlier on your third issue it automatically get your items.dat inside your Growtopia cache folder

**Comment by GuckTubeYT** [comment]
ok, items dat is read, but i got error
Exception in thread "main" java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
                                                                                                                        19:06:07 [INFO]         at me.droreo002.tools.ItemDataDecoder.main(ItemDataDecoder.java:55)

**Comment by DrOreo002** [comment]
> ok, items dat is read, but i got error
> Exception in thread "main" java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
> 19:06:07 [INFO] at me.droreo002.tools.ItemDataDecoder.main(ItemDataDecoder.java:55)

Lmao, I said it like 3 times already. I DO NOT KNOW and I FAILED TO REPLICATE your issue. Google is your friend :D
